import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { Store } from '../server/store';
import { World } from '../server/world';
import { migrateWorld } from '../server/migrations';
import { createWorld } from '../server/seed';
import { location, pathfind, walkable, TOWN_OFFSET, MAP_W, MAP_H } from '../shared/map';
import { outdoorActivities } from '../shared/outdoors';
import { advanceOutdoor } from '../server/outdoor-engine';
function setup(){const dir=mkdtempSync(join(tmpdir(),'valley-outdoors-')),store=new Store(dir),world=new World(store,'demo');for(const a of world.state.actors){a.nextDecision=1e9;a.nextPlan=1e9;}return {world,store,close:()=>{store.close();rmSync(dir,{recursive:true,force:true});}};}
function arrive(world:World,place:string){Object.assign(world.state.player,location(place).door);world.state.player.path=[];advanceOutdoor(world);}
test('expanded map is nine times larger and every activity destination is connected',()=>{assert.equal(MAP_W*MAP_H,80*60*9);for(const spec of Object.values(outdoorActivities))for(const id of spec.places){const path=pathfind(location('market').door,location(id).door);assert.ok(path.length,id);assert.ok(path.every(p=>walkable(p.x,p.y)),id);}assert.equal(walkable(100,176),false);assert.equal(walkable(36,94),false);assert.equal(walkable(34,21),false);});
test('legacy world migration offsets characters exactly once and preserves memory, relationships, inventory',()=>{const old=createWorld();old.version=1;old.player.x=36;old.player.y=36;old.actors[0].x=18;old.actors[0].y=22;old.player.inventory.wood=29;const text=JSON.stringify(old.actors[0].memories),rel=JSON.stringify(old.actors[0].relations);migrateWorld(old);assert.equal(old.player.x,36+TOWN_OFFSET.x);assert.equal(old.actors[0].y,22+TOWN_OFFSET.y);assert.equal(old.player.inventory.wood,29);assert.equal(JSON.stringify(old.actors[0].memories),text);for(const [id,r]of Object.entries(JSON.parse(rel)))assert.deepEqual(old.actors[0].relations[id],r);assert.equal(old.actors.length,24);migrateWorld(old);assert.equal(old.player.x,108);});
test('fishing consumes bait only after arrival and awards one persisted outcome',()=>{const f=setup();try{const {world}=f;world.resume();const before=world.state.player.inventory.bait;world.startOutdoor('player','fishing','seapier');assert.equal(world.state.player.inventory.bait,before);assert.equal(world.state.player.outdoor.task?.phase,'travel');arrive(world,'seapier');assert.equal(world.state.player.inventory.bait,before-1);world.state.clock+=26;advanceOutdoor(world);const xp=world.state.player.outdoor.xp.fishing,count=world.state.player.inventory.seafish??0;assert.ok(xp>0);advanceOutdoor(world);assert.equal(world.state.player.outdoor.xp.fishing,xp);assert.equal(world.state.player.inventory.seafish??0,count);assert.equal(world.state.player.outdoor.task,null);assert.equal(f.store.load()?.player.outdoor.xp.fishing,xp);}finally{f.close();}});
test('global pause freezes outdoor activity and restart preserves its deadline',()=>{const f=setup();try{const {world}=f;world.resume();world.startOutdoor('player','jogging','sports');arrive(world,'sports');world.pause();const deadline=world.state.player.outdoor.task?.endsAt;world.tick(600);assert.equal(world.state.player.outdoor.xp.fitness,0);assert.equal(world.state.player.outdoor.task?.endsAt,deadline);const restarted=new World(f.store,'demo');assert.equal(restarted.state.player.outdoor.task?.endsAt,deadline);assert.equal(restarted.state.status,'paused_manual');}finally{f.close();}});
test('activity prerequisites, occupied state and cancellation cannot duplicate rewards',()=>{const f=setup();try{const {world}=f;world.resume();world.state.player.inventory.bait=0;assert.throws(()=>world.startOutdoor('player','fishing','lakepier'),/鱼饵/);assert.throws(()=>world.startOutdoor('player','fishing','sports'),/不支持/);world.state.player.energy=2;assert.throws(()=>world.startOutdoor('player','hunting','huntingcamp'),/体力/);world.state.player.energy=100;world.state.clock=1200;assert.throws(()=>world.startOutdoor('player','hunting','huntingcamp'),/06:00/);world.state.clock=480;world.startOutdoor('player','hunting','huntingcamp');assert.throws(()=>world.startOutdoor('player','jogging','sports'),/已经/);arrive(world,'huntingcamp');const arrows=world.state.player.inventory.arrows;world.cancelOutdoor('player');world.state.clock+=100;advanceOutdoor(world);assert.equal(world.state.player.outdoor.xp.hunting,0);assert.equal(world.state.player.inventory.arrows,arrows);}finally{f.close();}});
test('sports and rest change stamina and fitness, NPC activities enter only witnessed memories',()=>{const f=setup();try{const {world}=f;world.resume();const a=world.actor('fisher');Object.assign(a,location('lakepier').door);world.startOutdoor(a.id,'fishing','lakepier');advanceOutdoor(world);world.state.clock+=26;advanceOutdoor(world);assert.ok(a.memories.at(-1)?.text.includes('镜湖'));assert.ok(!world.actor('baker').memories.some(m=>m.text.includes('镜湖')));world.startOutdoor('player','basketball','court');arrive(world,'court');assert.equal(world.state.player.energy,82);world.state.clock+=36;advanceOutdoor(world);assert.equal(world.state.player.outdoor.xp.fitness,10);world.startOutdoor('player','rest','square');arrive(world,'square');world.state.clock+=26;advanceOutdoor(world);assert.equal(world.state.player.energy,100);}finally{f.close();}});
