import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { Store } from '../server/store';
import { World } from '../server/world';
import { fastContext, realtimeLimits } from '../server/realtime';
import { estimateTokens, type Question, type JevResult } from '../server/models';
const flush=()=>new Promise<void>(resolve=>setImmediate(resolve));
function setup(){const dir=mkdtempSync('/private/tmp/valley-realtime-'),store=new Store(dir),w=new World(store,'live');for(const a of w.state.actors){a.nextPlan=1e9;a.nextDecision=1e9;}w.gateway.jev=async(_state,q)=>answer(q);w.resume();return {w,store,close(){store.close();rmSync(dir,{recursive:true,force:true});}};}
function answer(q:Record<string,Question>):JevResult{return {answers:Object.fromEntries(Object.entries(q).map(([id,spec])=>[id,spec.type==='choice'?{type:'choice',choice:('wait' in spec.criteria?'wait':'respond' in spec.criteria?'respond':Object.keys(spec.criteria)[0]),confidence:1,probabilities:{}}:spec.type==='score'?{type:'score',score:1,confidence:1}:{type:'noul',noul:1}])),model:'test-jev',input:1,output:1,latency:3};}
test('slow background planning allows concurrent Jev decisions and game time',async()=>{const f=setup(),finishes:((r:any)=>void)[]=[];try{const {w}=f;const actors=w.state.actors.slice(0,6);for(const a of actors){a.nextPlan=0;a.nextDecision=0;}w.gateway.text=async()=>new Promise(resolve=>finishes.push(resolve));w.tick(.1);await flush();assert.equal(w.lanes.background,realtimeLimits.background);assert.equal(w.lanes.action,0);assert.equal(w.state.decisions.filter(d=>d.source==='test-jev').length,6);assert.equal(actors[0].busy,false);const clock=w.state.clock;w.tick(.1);assert.ok(w.state.clock>clock);assert.equal(w.snapshot().timing.waitingForApi,false);w.pause();finishes.forEach(resolve=>resolve({text:'后台计划',input:1,output:1,latency:9,model:'test-text'}));await flush();assert.equal(w.active,0);assert.equal(w.state.pending.filter(p=>p.kind==='plan').length,realtimeLimits.background);}finally{f.close();}});
test('three slow dialogues leave fast slots available, pending speech is private, and paused results wait for resume',async()=>{const f=setup(),finishes:((r:any)=>void)[]=[];try{const {w}=f;const pairs=[['baker','gardener'],['carpenter','merchant'],['librarian','fisher']];for(const pair of pairs){for(const id of pair)Object.assign(w.actor(id),{x:108,y:80});w.startConversation(pair[0],pair[1]);}w.gateway.text=async()=>new Promise(resolve=>finishes.push(resolve));w.actor('innkeeper').nextDecision=0;w.tick(.1);await flush();assert.equal(w.lanes.dialogue,3);assert.equal(w.lanes.action,0);assert.ok(w.state.decisions.some(d=>d.actorId==='innkeeper'));assert.equal(w.snapshot(true).bubbles.filter(b=>b.pending).length,3);assert.deepEqual(w.snapshot(false).bubbles,[]);w.pause();finishes.forEach(resolve=>resolve({text:'今天的风很舒服。',input:1,output:1,latency:4,model:'test'}));await flush();assert.equal(w.state.speechQueue.length,3);assert.ok(!w.snapshot(true).bubbles.some(b=>b.text));w.resume();for(const c of w.state.conversations)c.nextTurn=1e9;w.tick(.1);w.pause();assert.equal(w.state.speechQueue.length,0);assert.equal(w.snapshot(true).bubbles.filter(b=>b.text).length,3);assert.deepEqual(w.snapshot(false).bubbles,[]);assert.equal(w.active,0);}finally{f.close();}});
test('idle player conversation allows time to advance and only committed speech becomes a bubble',async()=>{const f=setup();try{const {w}=f;const a=w.actor('gardener');Object.assign(w.state.player,{x:a.x,y:a.y});const c=w.startConversation('player',a.id);const before=w.state.clock;w.tick(1);assert.ok(w.state.clock-before>.7);assert.deepEqual(w.snapshot(false).bubbles,[]);w.gateway.text=async()=>({text:'一起听听风里的声音吧。',model:'text-test',input:1,output:1,latency:5});w.sendMessage(c.id,'你好');await flush();const bubbles=w.snapshot(false).bubbles;assert.ok(bubbles.some(b=>b.actorId===a.id&&b.text==='一起听听风里的声音吧。'));assert.equal(w.snapshot(true).bubbles.some(b=>b.text.includes(a.secret.core)),false);w.pause();assert.equal(w.active,0);}finally{f.close();}});
test('fast context is bounded, includes only target relations, and never changes full memory storage',()=>{const f=setup();try{const {w}=f,a=w.actor('gardener');for(let i=0;i<50;i++)w.memory(a,`经历${i}：`+'这是一段当天实际发生并留存的个人记忆。'.repeat(20),'test',i%2===0);const before=JSON.stringify(a.memories),small=fastContext(w.state,a,['baker']);assert.deepEqual(Object.keys(small.ownRelations),['baker']);assert.ok(estimateTokens(small)<estimateTokens(w.privateContext(a))*.55);assert.equal(JSON.stringify(a.memories),before);assert.ok(!JSON.stringify(small).includes(w.actor('baker').secret.core));}finally{f.close();}});
