import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { World } from '../server/world';
import { Store } from '../server/store';
import { advanceSociety, canMarry, canHaveChild, commitFamily, considerFamily, commitMurder } from '../server/society';
import { location, walkable, pathfind } from '../shared/map';
function setup(){const dir=mkdtempSync(join(tmpdir(),'valley-society-')),store=new Store(dir),w=new World(store,'demo');w.resume();return {w,store,close(){store.close();rmSync(dir,{recursive:true,force:true});}};}
function couple(w:World){const a=w.actor('doctor'),b=w.actor('teacher');Object.assign(a,location('square').door);Object.assign(b,{x:a.x+1,y:a.y});return {a,b};}
async function marry(w:World){const {a,b}=couple(w);commitFamily(w,a,await considerFamily(w,a,b,'marriage'));return {a,b};}
test('migration yields 24 unique adults and independently editable, private secrets without reseeding on restart',()=>{const f=setup();try{const {w}=f;assert.equal(w.state.actors.length,24);assert.equal(new Set(w.state.actors.map(a=>a.secret.core)).size,24);assert.ok(w.state.actors.every(a=>a.life.stage==='adult'&&a.age>=18));w.actor('doctor').memories.push({id:'remember',day:1,minute:480,text:'记住我',source:'test',kind:'experience',important:true});w.pause();const restored=new World(f.store);assert.equal(restored.state.actors.length,24);assert.equal(restored.actor('doctor').memories.at(-1)?.text,'记住我');assert.equal(restored.documents.list('doctor').length,4);const publicView=restored.snapshot(false);assert.ok(!JSON.stringify(publicView).includes(restored.actor('doctor').secret.core));assert.equal((publicView.actors[0].life as any).aggressive,undefined);}finally{f.close();}});
test('marriage requires separate consent, revalidates both revisions, and does not share private memories',async()=>{const f=setup();try{const {w}=f,{a,b}=couple(w);let calls:string[]=[];const evaluate=w.evaluate.bind(w);w.evaluate=async(actor,state,q,p,preferred)=>{calls.push(actor.id);assert.ok(!JSON.stringify(state).includes((actor.id===a.id?b:a).secret.core));return evaluate(actor,state,q,p,actor.id===b.id?'decline':preferred);};const declined=await considerFamily(w,a,b,'marriage');commitFamily(w,a,declined);assert.deepEqual(calls,[a.id,b.id]);assert.equal(a.life.spouse,null);w.evaluate=evaluate;const stale=await considerFamily(w,a,b,'marriage');b.revision++;commitFamily(w,a,stale);assert.equal(a.life.spouse,null);commitFamily(w,a,await considerFamily(w,a,b,'marriage'));assert.equal(a.life.spouse,b.id);assert.equal(b.life.spouse,a.id);assert.equal(w.state.events.filter(e=>e.kind==='marriage').length,1);commitFamily(w,a,await considerFamily(w,a,b,'marriage'));assert.equal(w.state.events.filter(e=>e.kind==='marriage').length,1);assert.ok(!JSON.stringify(a.memories).includes(b.secret.core));b.life.stage='child';assert.equal(canMarry(a,b),false);}finally{f.close();}});
test('birth survives paused restart, occurs once, creates a child with documents and complete relationships',async()=>{const f=setup();try{let w=f.w;const {a,b}=await marry(w);commitFamily(w,a,await considerFamily(w,a,b,'family'));assert.equal(w.state.society.births.length,1);assert.equal(canHaveChild(w,a,b),false);const due=w.state.society.births[0].dueAt;w.state.clock=due;w.pause();advanceSociety(w);assert.equal(w.state.actors.length,24);w=new World(f.store);w.resume();advanceSociety(w);advanceSociety(w);assert.equal(w.state.actors.length,25);const child=w.state.actors.at(-1)!;assert.equal(child.life.stage,'child');assert.deepEqual(child.life.parents,[a.id,b.id]);assert.equal(w.state.events.filter(e=>e.kind==='birth').length,1);assert.equal(w.documents.list(child.id).length,4);assert.ok(w.state.actors.filter(p=>p.id!==child.id).every(p=>p.relations[child.id]&&child.relations[p.id]));assert.throws(()=>w.requestSocial('player',child.id,'confess'),/儿童/);assert.throws(()=>w.startOutdoor(child.id,'hunting','huntingcamp'),/儿童/);assert.equal(canHaveChild(w,w.actor(a.id),w.actor(b.id)),true);}finally{f.close();}});
test('murder invalidates victim activity and appointments; unproven identity stays out of public snapshot',()=>{const f=setup();try{const {w}=f,a=w.actor('miner'),b=w.actor('broker');Object.assign(a,location('square').door);Object.assign(b,{x:a.x+1,y:a.y});w.state.appointments.push({id:'future',from:b.id,to:'teacher',place:'riverside',at:w.state.clock+10,status:'accepted',type:'date',arrived:[]});b.path=[{x:108,y:81}];const revision=b.revision;assert.equal(commitMurder(w,a,b),true);assert.equal(commitMurder(w,a,b),false);assert.equal(b.life.status,'dead');assert.ok(b.revision>revision);assert.equal(b.path.length,0);assert.equal(w.state.appointments[0].status,'declined');assert.throws(()=>w.startConversation('player',b.id),/已故/);assert.throws(()=>w.gift(b.id,'bread'),/已故/);assert.equal((w.snapshot().society.cases[0] as any).perpetrator,undefined);assert.equal((w.snapshot().society.cases[0] as any).evidence,undefined);assert.equal(w.privateContext(w.actor('teacher')).memories.some(m=>m.text.includes('我导致')),false);}finally{f.close();}});
test('evidence gates custody, prison confines routines, weather cannot release inmates, sentence and release are idempotent',()=>{const f=setup();try{const {w}=f,a=w.actor('miner'),b=w.actor('broker');Object.assign(a,{x:180,y:130});Object.assign(b,{x:181,y:130});commitMurder(w,a,b);const c=w.state.society.cases[0];assert.equal(c.evidence.length,1);w.state.rng=1200;w.state.clock=c.nextInvestigation;advanceSociety(w);assert.equal(c.status,'unresolved');assert.equal(a.life.custody,null);c.evidence.push({kind:'独立目击证词',witness:'guard',at:w.state.clock});w.state.clock=c.nextInvestigation;advanceSociety(w);assert.equal(c.status,'sentenced');assert.ok(a.life.custody);assert.throws(()=>w.startOutdoor(a.id,'jogging','sports'),/服刑/);const release=c.releaseAt!;assert.ok(a.path.every(p=>p.x>150&&p.x<165&&p.y>94&&p.y<106));w.state.weather='晴朗';w.state.weatherSlot=-1;w.updateWeather();assert.ok(a.life.custody);w.state.clock=release;w.pause();advanceSociety(w);assert.ok(a.life.custody);w.resume();advanceSociety(w);advanceSociety(w);assert.equal(c.status,'released');assert.equal(a.life.custody,null);assert.equal(w.state.events.filter(e=>e.kind==='release').length,1);assert.ok(walkable(a.x,a.y));assert.ok(pathfind(a,location('square').door).length);}finally{f.close();}});
test('death or imprisonment cancels a planned birth; the family cap prevents unbounded population',async()=>{const f=setup();try{const {w}=f,{a,b}=await marry(w);commitFamily(w,a,await considerFamily(w,a,b,'family'));a.life.custody={caseId:'test',releaseAt:99999};w.state.clock=w.state.society.births[0].dueAt;advanceSociety(w);assert.equal(w.state.actors.length,24);assert.equal(w.state.society.births.length,0);a.life.custody=null;a.life.children=['one','two'];assert.equal(canHaveChild(w,a,b),false);}finally{f.close();}});
