import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { World } from '../server/world';
import { Store } from '../server/store';
import { daylight, weatherAt, weatherSlot, weatherInfo } from '../shared/weather';
import { location } from '../shared/map';
import { advanceOutdoor } from '../server/outdoor-engine';
function setup(){const dir=mkdtempSync(join(tmpdir(),'valley-weather-')),store=new Store(dir),world=new World(store,'demo');for(const a of world.state.actors){a.nextDecision=1e9;a.nextPlan=1e9;}return {world,store,close(){store.close();rmSync(dir,{recursive:true,force:true});}};}
test('weather fronts are deterministic, diverse and daylight is continuous through dawn and dusk',()=>{const seen=new Set();for(let c=0;c<5760;c+=240){seen.add(weatherAt(c));assert.equal(weatherAt(c),weatherAt(c+239));}assert.equal(seen.size,5);assert.equal(daylight(720).sun,1);assert.equal(daylight(0).sun,0);assert.equal(daylight(1439.99).night,daylight(0).night);for(const c of [300,480,1020,1200])assert.ok(Math.abs(daylight(c-.01).sun-daylight(c+.01).sun)<.001);});
test('weather transitions persist, inform Jev without scheduling DS, and remain frozen while paused and after restart',()=>{const f=setup();try{const w=f.world;w.state.clock=1440+720;const before=w.actor('baker').memories.length;w.updateWeather();assert.equal(w.state.weather,'雷雨');assert.equal(w.actor('baker').nextDecision,w.state.clock);assert.equal(w.actor('baker').nextPlan,1e9);assert.ok(w.actor('baker').planning?.issues.some(i=>i.code==='weather'));assert.equal(w.actor('baker').memories.length,before+1);w.pause();const slot=w.state.weatherSlot;w.tick(30000);assert.equal(w.state.weatherSlot,slot);const restarted=new World(f.store);assert.equal(restarted.state.weather,'雷雨');assert.equal(restarted.state.weatherSlot,slot);assert.equal(restarted.state.status,'paused_manual');}finally{f.close();}});
test('bad weather blocks new activities and cancels active tasks without double charging or rewards',()=>{const f=setup();try{const w=f.world;w.resume();w.state.weather='大雾';assert.throws(()=>w.startOutdoor('player','hiking','summit'),/大雾/);assert.throws(()=>w.startOutdoor('player','hunting','huntingcamp'),/大雾/);w.state.weather='晴朗';Object.assign(w.state.player,location('seapier').door);w.startOutdoor('player','fishing','seapier');advanceOutdoor(w);const bait=w.state.player.inventory.bait;w.state.weather='雷雨';advanceOutdoor(w);assert.equal(w.state.player.outdoor.task,null);assert.match(w.state.player.outdoor.lastResult!.text,/雷雨/);assert.equal(w.state.player.inventory.bait,bait);assert.equal(w.state.player.outdoor.xp.fishing,0);assert.throws(()=>w.startOutdoor('player','jogging','sports'),/雷雨/);advanceOutdoor(w);assert.equal(w.state.player.inventory.bait,bait);}finally{f.close();}});
test('rain affects movement and stamina, while retaining the fishing benefit',()=>{const f=setup();try{const w=f.world;w.resume();w.state.weather='细雨';w.state.weatherSlot=weatherSlot(w.state.clock);Object.assign(w.state.player,location('sports').door);w.startOutdoor('player','jogging','sports');advanceOutdoor(w);assert.equal(w.state.player.energy,100-Math.ceil(14*1.2));w.cancelOutdoor('player');w.state.player.path=[{x:w.state.player.x+10,y:w.state.player.y}];const x=w.state.player.x;w.tick(1);assert.ok(Math.abs(w.state.player.x-x-5*.88)<.001);assert.ok(weatherInfo('细雨').fishBonus>weatherInfo('晴朗').fishBonus);}finally{f.close();}});
test('Jev receives weather and legal choices; delayed clear-weather decisions revalidate in a storm',async()=>{const f=setup();try{const w=f.world;w.resume();const a=w.actor('carpenter');w.state.weather='雷雨';let captured:any;const evaluate=w.evaluate.bind(w);w.evaluate=async(actor,state,questions,purpose,preferred)=>{captured={state,questions};return evaluate(actor,state,questions,purpose,preferred);};await w.chooseAction(a);assert.equal(captured.state.environment.weather,'雷雨');assert.ok(captured.questions.action.criteria.shelter);assert.ok(!Object.keys(captured.questions.action.criteria).some(k=>k.startsWith('hunting_')||k==='riverside'));assert.match(a.activity,/避雨|屋檐/);w.state.weather='晴朗';a.path=[];Object.assign(a,location('huntingcamp').door);w.evaluate=async(_a,_state,q)=>{assert.equal(q.action.type,'choice');if(q.action.type!=='choice')throw new Error('Expected choice');const key=Object.keys(q.action.criteria).find(k=>k.startsWith('hunting_'))!;assert.ok(key);w.state.weather='雷雨';return {answers:{action:{type:'choice',choice:key,confidence:1,probabilities:{[key]:1}}},model:'test',input:0,output:0,latency:0};};await w.chooseAction(a);assert.equal(a.outdoor.task,null);assert.match(a.activity,/避雨|屋檐/);assert.equal(w.store.usage().used,0);}finally{f.close();}});
test('storm postpones appointments instead of punishing residents for weather',()=>{const f=setup();try{const w=f.world;w.resume();w.state.weather='雷雨';const a=w.actor('baker'),b=w.actor('gardener');w.state.appointments.push({id:'storm-date',from:a.id,to:b.id,place:'riverside',at:w.state.clock,status:'accepted',type:'date',arrived:[a.id]});const trust=a.relations[b.id].trust;w.tick(.1);const date=w.state.appointments[0];assert.equal(date.status,'accepted');assert.ok(date.at>w.state.clock);assert.equal(date.arrived.length,0);assert.equal(a.relations[b.id].trust,trust);assert.ok(a.memories.some(m=>m.text.includes('因雷雨')));}finally{f.close();}});
