import { freshIncidents } from '../shared/incidents';
import { TOWN_OFFSET } from '../shared/map';
import { emptyOutdoor } from '../shared/outdoors';
import { freshLife, relation, type Actor, type WorldState, type Mode } from '../shared/types';
const seeds = [
  ['baker','林穗','面包师',27,'#ca8d6e','#654336','bakery',18,22,'温和认真，喜欢用具体小事关心别人。忙碌时简短回应，不愿公开讨论家庭财务。','让面包店自给自足，准备晚灯集市的订单。','每月匿名偿还父亲的旧债，怕别人同情或误解自己的经营能力。','最近订单很多，有一点压力。','每个月有一笔不能动的固定支出。'],
  ['gardener','许棠','园丁',26,'#779a72','#684a37','garden',20,29,'开朗但有分寸，熟悉后会轻轻打趣。重视守约、独立选择和实际帮助，讨厌空口承诺。','建成公共花园，保护施工旁的花圃。','获得外地植物园的职位邀请，还没回信，担心离开会伤害在意的人。','有时想看看外面的世界。','最近有一个需要认真决定的机会。'],
  ['carpenter','周砚','木匠',30,'#7093a3','#4b4240','workshop',50,46,'寡言务实，遇到自己的错误会防御。欣赏共同劳动，不接受当众羞辱。','补齐木料，修好旧桥，重新得到大家信任。','当年维护旧桥时因赶工跳过检查，怀疑自己对桥损坏有责任。','对旧桥的结构很熟悉。','对当年的一次维护有遗憾。'],
  ['merchant','沈禾','杂货店主',29,'#c1a065','#4b4036','market',35,22,'精明幽默，习惯谈交换条件，重视守约。现金流紧张但不想示弱。','保住杂货铺，完成集市采购。','知道一批木材有瑕疵，却因为资金紧张延后召回通知，害怕失去信任。','最近进货有些压力。','有一笔旧生意让人不安。'],
  ['librarian','顾言','图书管理员',28,'#8e91b0','#443b34','library',49,23,'克制细心，关心别人却不急于表态。喜爱旧书与具体反馈，拒绝未经允许查看手稿。','办好读书会，希望作品获得认真评价。','镇上匿名连载故事是自己写的，其中一位人物寄托了对林穗的感情。','空闲时也会写一点东西。','对镇上的匿名连载有特别的感情。'],
  ['fisher','江屿','渔夫',31,'#76a9ab','#6c523a','riverside',69,30,'爽快爱开玩笑，紧张时话更多。讨厌被逼证明勇敢，珍惜可靠伙伴。','改善码头并保持稳定收入。','曾在水上事故失去伙伴，惧怕深水却装成无所畏惧。','不喜欢某段河道。','以前出过一次不愿谈的事故。'],
  ['innkeeper','温岚','旅店经营者',34,'#ae8090','#584337','inn',21,47,'善于照顾场面，会自然转移尴尬话题。希望有人听自己的愿望，不愿做消息中转站。','准备晚灯集市，留住旅店老客。','收到很诱人的旅店收购报价，想过离开，但担心大家觉得她抛弃了小镇。','最近有些睡不好。','收到了一封会影响未来的来信。'],
  ['painter','陆青','画师',25,'#baa075','#805438','library',41,31,'好奇敏感，热情和退缩交替，喜欢真诚的创作反馈，不愿被与名家比较。','完成一场属于自己的小镇画展。','曾用别名提交模仿导师构图的画作，获奖后主动退赛，如今怕过去被翻出。','不想谈以前的画展。','以前有过让自己后悔的创作决定。'],
] as const;
export function createWorld(mode:Mode='demo'):WorldState {
  const actors:Actor[]=seeds.map(s=>({life:freshLife(),id:s[0],name:s[1],role:s[2],age:s[3],color:s[4],hair:s[5],skin:'#e9ba8d',home:s[6],x:s[7]+TOWN_OFFSET.x,y:s[8]+TOWN_OFFSET.y,outdoor:emptyOutdoor(),persona:s[9],goal:s[10],plan:'上午完成自己的工作，午后留一点时间与邻居交流。',secret:{title:'心底的秘密',core:s[11],fragments:[s[12],s[13],s[11]],disclosed:{}},knowledge:[],activity:'准备新的一天',energy:88,mood:'平静',actionUntil:480,nextDecision:480,nextPlan:480,revision:1,target:null,path:[],conversation:null,busy:false,inventory:{bread:2,flowers:2,wood:3,note:2,rod:1,bait:8,bow:s[0]==='carpenter'||s[0]==='fisher'?1:0,arrows:6,...s[0]==='merchant'?{rod:8,bait:100,bow:5,arrows:100}:{}},coins:30,relations:{},memories:[{id:`seed-${s[0]}`,day:1,minute:480,text:'晚灯集市即将到来，想把手头的事情做好。',source:'初始设定',kind:'editor',important:true}],partner:null,trustedEvents:{},giftCounts:{},socialCooldown:{}}));
  for(const a of actors) for(const id of [...actors.map(b=>b.id),'player']) if(id!==a.id)a.relations[id]=relation();
  for(const [from,to,aff,trust,attract] of [['librarian','baker',45,55,55],['baker','librarian',30,50,15],['carpenter','gardener',35,45,40],['gardener','carpenter',25,45,20],['carpenter','merchant',-25,20,0],['merchant','carpenter',-10,30,0],['fisher','innkeeper',40,65,25],['innkeeper','fisher',35,60,20],['gardener','baker',45,65,0]] as const) Object.assign(actors.find(a=>a.id===from)!.relations[to],{affection:aff,trust,attraction:attract,familiarity:60,resentment:aff<0?30:0});
  return {society:{requests:[],nextPulse:480,lastMurderDay:-100,births:[],cases:[],dailyFamily:{},nextChild:1},version:2,id:'creek-valley',clock:480,dayMinutes:30,incidents:freshIncidents(480),status:'paused_manual',mode,weather:'晴朗',actors,player:{x:36+TOWN_OFFSET.x,y:36+TOWN_OFFSET.y,energy:100,outdoor:emptyOutdoor(),path:[],coins:80,inventory:{rod:1,bait:12,bow:1,arrows:8,flowers:3,bread:3,wood:8,note:3,seeds:3},conversation:null},events:[{id:'welcome',at:480,kind:'town',text:'新的一天，溪谷镇醒来了。晚灯集市正在筹备中。',actorIds:[],audience:['public'],mode:'live'}],conversations:[],appointments:[],quests:[{id:'bridge',title:'一起修好旧桥',text:'帮助居民收集木料并完成修理。',progress:0,required:30,completed:false,reward:40},{id:'festival',title:'晚灯集市',text:'准备花束与面包，让广场热闹起来。',progress:0,required:20,completed:false,reward:25}],decisions:[],checkpointAt:Date.now(),reflectionQueue:[],commandIds:[],commandResults:{},speechQueue:[],pending:[],notice:'小镇已准备好。点击「开始生活」，或先了解一位村民。'};
}
