import { BudgetSettings } from './BudgetSettings';
import { budgetProviders, money } from '../shared/budget';
import { ActorStory } from './ActorStory';
import { SimulationSpeed } from './SimulationSpeed';
import { DecisionLab } from './DecisionLab';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, BookOpen, Check, ChevronDown, Clock3, Coins, Eye, Flower2, Heart, Leaf, MapPin, MessageCircle, Pause, Play, RefreshCw, Send, Settings2, Shield, Sparkles, Sun, Users, X, Backpack, Flag, CloudRain, FileText, LockKeyhole, CircleHelp, Save, Radio, Zap, Compass, BatteryMedium, Footprints, Moon, Cloud, CloudFog, CloudLightning, Maximize2, Minimize2 } from 'lucide-react';
import type { Actor, DocumentView, PublicActor, Snapshot } from '../shared/types';
import { dayOf, timeOf } from '../shared/types';
import { distance, items, location, locations, regionAt } from '../shared/map';
import { useImmersive } from './useImmersive';
import { daylight, weatherInfo } from '../shared/weather';
import { TownCanvas } from './TownCanvas';
import { OutdoorPanel } from './OutdoorPanel';
import { outdoorActivities } from '../shared/outdoors';

async function api<T=any>(path:string,body?:unknown):Promise<T>{const response=await fetch(`/api${path}`,body===undefined?undefined:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data;}
const compact=(n:number)=>n>=1e6?`${(n/1e6).toFixed(2)}M`:n>=1000?`${(n/1000).toFixed(1)}k`:String(n);
const running=(s:Snapshot)=>s.status==='running_live';
const tags:Record<string,string>={baker:'温柔 · 认真',gardener:'开朗 · 独立',carpenter:'寡言 · 务实',merchant:'幽默 · 精明',librarian:'克制 · 细心',fisher:'爽快 · 可靠',innkeeper:'体贴 · 坚定',painter:'敏感 · 好奇'};
function Avatar({actor,large=false}:{actor:PublicActor;large?:boolean}){return <div className={`avatar ${large?'large':''}`} style={{background:`${actor.color}28`}}><svg viewBox="0 0 40 44" role="img" aria-label={`${actor.name}像素头像`} shapeRendering="crispEdges"><path d="M8 39h25v5H8z" fill={actor.color}/><path d="M10 28h22v16H10zM5 32h8v12H5zM30 32h7v12h-7z" fill={actor.color}/><path d="M17 24h9v7h-9zM11 9h21v18H11z" fill={actor.skin}/><path d="M9 7h25v9h-5v-3H14v5H9zM8 12h5v13H8zM31 14h4v10h-4z" fill={actor.hair}/><path d="M15 19h3v3h-3zM26 19h3v3h-3z" fill="#493a32"/><path d="M12 24h5v2h-5zM27 24h4v2h-4z" fill="#d79e85"/>{actor.id==='gardener'&&<><path d="M5 9h32v5H5zM11 3h21v8H11z" fill="#b8ac77"/><path d="M11 8h21v3H11z" fill="#697a4f"/></>}{actor.id==='baker'&&<><path d="M8 6h28v7H8zM12 0h20v8H12z" fill="#f4eddf"/><path d="M16 29h11v15H16z" fill="#eee5d0"/></>}</svg></div>;}
function Modal({title,children,close,wide=false}:{title:string;children:React.ReactNode;close:()=>void;wide?:boolean}){
  const ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.querySelector<HTMLElement>('button,input,textarea,select')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=Array.from(ref.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input,textarea,select,[tabindex="0"]')??[]);if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[]);
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><div className={`modal ${wide?'wide':''}`} ref={ref} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="关闭"><X size={20}/></button></header>{children}</div></div>;
}

export function App(){
  const {root,button:fullscreenButton,immersive,toggle:toggleFullscreen}=useImmersive();
  const [world,setWorld]=useState<Snapshot|null>(null),[observer,setObserver]=useState(true),[selected,setSelected]=useState('gardener');
  const [connected,setConnected]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('profile');
  const [modal,setModal]=useState<'settings'|'inventory'|'quests'|'docs'|'help'|'saves'|'outdoors'|'society'|'lab'|'story'|null>(null);
  const [text,setText]=useState(''),[sending,setSending]=useState(false),[docs,setDocs]=useState<DocumentView[]>([]),[docIndex,setDocIndex]=useState(0),[docText,setDocText]=useState(''),[saveList,setSaveList]=useState<any[]>([]);
  const [autoTalk,setAutoTalk]=useState<string|null>(null),[eventFilter,setEventFilter]=useState('all');
  const latest=useRef(world);latest.current=world;
  const chatBottom=useRef<HTMLDivElement>(null);
  const notify=(message:string)=>{setError(message);};
  const run=async(fn:()=>Promise<any>)=>{try{return await fn();}catch(e){notify((e as Error).message);}};
  const changeSpeed=useCallback((dayMinutes:number)=>api('/control',{action:'speed',value:dayMinutes}),[]);
  const command=useCallback((type:string,params:Record<string,unknown>={})=>api('/commands',{commandId:crypto.randomUUID(),type,...params}),[]);
  useEffect(()=>{
    let stopped=false,socket:WebSocket|undefined,timer:ReturnType<typeof setTimeout>;
    const connect=async()=>{try{await api('/bootstrap');const w=await api<Snapshot>(`/world?view=${observer?'observer':'player'}`);if(stopped)return;setWorld(w);socket=new WebSocket(`${locationProtocol()}//${window.location.host}/api/live?view=${observer?'observer':'player'}`);socket.onopen=()=>setConnected(true);socket.onmessage=e=>{if(!stopped)setWorld(JSON.parse(e.data));};socket.onerror=()=>socket?.close();socket.onclose=()=>{setConnected(false);if(!stopped)timer=setTimeout(connect,1800);};}catch(e){if(!stopped){setError('正在连接本地小镇服务…');timer=setTimeout(connect,2000);}}};void connect();return()=>{stopped=true;clearTimeout(timer);socket?.close();};
  },[observer]);
  useEffect(()=>{if(!error)return;const t=setTimeout(()=>setError(''),6500);return()=>clearTimeout(t);},[error]);
  useEffect(()=>{if(!autoTalk)return;let pending=false,stopped=false;const follow=async()=>{const w=latest.current;if(stopped||pending||!w||!running(w))return;if(w.player.conversation){setAutoTalk(null);return;}const a=w.actors.find(a=>a.id===autoTalk);if(!a)return;pending=true;try{if(distance(w.player,a)<4){if(!a.busy){await command('talk',{target:a.id});if(!stopped)setAutoTalk(null);}}else await command('move',{x:Math.round(a.x),y:Math.round(a.y)+1});}catch{/* The target may move or be occupied. Retry while following. */}finally{pending=false;}};const timer=setInterval(()=>void follow(),1000);void follow();return()=>{stopped=true;clearInterval(timer);};},[autoTalk,command]);
  const conversation=world?.conversations.find(c=>c.id===world.player.conversation&&c.status==='active');
  useEffect(()=>{chatBottom.current?.scrollIntoView({block:'nearest'});},[conversation?.messages.length,conversation?.pending]);
  const openDocs=async()=>{await run(async()=>{const rows=await api<DocumentView[]>(`/documents/${selected}`);setDocs(rows);setDocIndex(0);setDocText(rows[0].text);setModal('docs');});};
  const interact=useCallback(()=>{const w=latest.current;if(!w)return;const nearest=w.actors.filter(a=>a.life.status==='alive'&&!a.life.custody).sort((a,b)=>distance(a,w.player)-distance(b,w.player))[0];if(nearest&&distance(nearest,w.player)<5){setSelected(nearest.id);void command('talk',{target:nearest.id}).catch(e=>setError(e.message));}else setError('走近村民，再按 E 开始交谈。');},[command]);
  if(!world)return <div className="loading-screen"><div className="brand-mark"><Leaf size={30}/></div><h1>溪谷镇</h1><p>沿着河流，等小镇慢慢醒来。</p><span className="loading-dots">正在连接本地世界服务</span>{error&&<small>{error}</small>}</div>;
  const actor=world.actors.find(a=>a.id===selected)??world.actors[0];
  const privateActor=world.privateActors?.find(a=>a.id===actor.id);
  const decision=world.decisions?.find(d=>d.actorId===actor.id);
  const recent=world.events.filter(e=>eventFilter==='all'||(eventFilter==='family'?['marriage','family','birth'].includes(e.kind):eventFilter==='justice'?['murder','justice','release','conflict'].includes(e.kind):eventFilter==='weather'?e.kind==='weather':eventFilter==='outdoor'?e.kind==='outdoor':e.kind==='relationship'||e.kind==='dialogue')).slice(-15).reverse();
  const rel=privateActor?.relations.player;
  const talk=()=>run(async()=>{if(!running(world))throw new Error('先开始生活，时间才能流动。');setAutoTalk(actor.id);});
  const send=async(e:React.FormEvent)=>{e.preventDefault();if(!text.trim()||sending||!conversation)return;setSending(true);const result=await run(()=>command('message',{target:conversation.id,text}));if(result)setText('');setSending(false);};
  const outdoorTask=world.player.outdoor.task;const outdoorProgress=outdoorTask?.phase==='active'?Math.min(100,(world.clock-outdoorTask.startedAt)/(outdoorTask.endsAt!-outdoorTask.startedAt)*100):0;
  const WeatherGlyph=world.weather==='雷雨'?CloudLightning:world.weather==='大雾'?CloudFog:world.weather==='细雨'?CloudRain:world.weather==='多云'?Cloud:daylight(world.clock).night>.7?Moon:Sun;
  const modeLabel=world.mode==='demo'?'规则演示 · 非模型':'Jev × DeepSeek';
  return <div ref={root} className={`app-shell ${immersive?'immersive':''}`}>
    <header className="topbar">
      <a className="brand" href="/" aria-label="溪谷镇首页"><div className="brand-mark"><Leaf size={23}/></div><div><strong>溪谷镇<span>VALLEYTOWN</span></strong><small>每个人，都有自己的故事。</small></div></a>
      <nav className="view-switch" aria-label="模式"><button className={!observer?'active':''} onClick={()=>{setObserver(false);setModal(null);setTab('profile');}}><MapPin size={15}/> 自由游玩</button><button className={observer?'active':''} onClick={()=>setObserver(true)}><Eye size={15}/> 观察者</button></nav>
      <div className="header-right"><span className={`connection ${connected?'online':''}`}><i/>{connected?'本地小镇已连接':'正在重连'}</span><button className="icon-button" aria-label="帮助与操作说明" onClick={()=>setModal('help')}><CircleHelp size={19}/></button><button className="icon-button" aria-label="设置" onClick={()=>setModal('settings')}><Settings2 size={19}/></button></div>
    </header>
    {world.laboratory?.active&&<div className="lab-running-banner" role="status">决策实验进行中 · {world.laboratory.completed} / {world.laboratory.total} · 世界时钟冻结 · 暂停模拟将停止后续请求</div>}
    <div className="world-toolbar">
      <div className="season"><div className="season-icon"><Flower2 size={21}/></div><div><strong>春 · 第 {dayOf(world.clock)} 天</strong><small>一段新的生活</small></div><span className="divider"/><span className="world-time"><Clock3 size={17}/>{timeOf(world.clock)}</span><span className="weather"><WeatherGlyph size={18}/> {world.weather}</span></div>
      <div className="simulation-controls"><span className={`model-badge ${world.mode==='demo'?'demo':''}`}><Sparkles size={13}/>{modeLabel}</span><SimulationSpeed world={world} onChange={changeSpeed}/><button className={`primary play-button ${running(world)?'running':''}`} onClick={()=>void run(()=>api('/control',{action:running(world)?'pause':'resume'}))}>{running(world)?<Pause size={15} fill="currentColor"/>:<Play size={15} fill="currentColor"/>}{running(world)?'暂停模拟':world.clock===480?'开始生活':'继续模拟'}</button></div>
    </div>
    <main className="workspace">
      <aside className="residents-panel">
        <div className="panel-title"><h2>小镇居民</h2><span className="count">{world.actors.filter(a=>a.life.status==='alive').length}</span></div><p className="panel-caption">{world.actors.filter(a=>a.life.status==='alive'&&a.life.stage==='adult').length} 位成年人 · {world.actors.filter(a=>a.life.stage==='child').length} 位孩子 · 各自的人生</p>
        <button className="outline full society-open" onClick={()=>setModal('society')}><Users size={15}/> 家庭与司法 <span>{world.society.cases.filter(c=>c.status==='investigating'||c.status==='unresolved').length} 案在查</span></button><div className="resident-list" role="region" aria-label="小镇居民列表" tabIndex={0}>{world.actors.map(a=><button key={a.id} className={`resident ${selected===a.id?'selected':''}`} onClick={()=>{setSelected(a.id);setTab('profile');}}><Avatar actor={a}/><span className="resident-copy"><strong>{a.name}<small>{a.role}</small></strong><span><i className={a.busy?'thinking-dot':'status-dot'}/>{a.busy?'正在思考':a.activity}</span></span>{selected===a.id&&<span className="resident-arrow">›</span>}</button>)}</div>
        <div className="left-bottom"><button className="explore-shortcut" onClick={()=>setModal('outdoors')}><Compass size={18}/><span>远行与活动<small>钓鱼 · 运动 · 打猎</small></span><ArrowRight size={14}/></button><div className="section-label">你的口袋</div><button className="inventory-shortcut" onClick={()=>setModal('inventory')}><Backpack size={18}/><span>背包与礼物</span><span className="coin-count"><Coins size={13}/>{world.player.coins}</span></button><button className="quest-shortcut" onClick={()=>setModal('quests')}><Flag size={16}/>小镇公告板<span>{world.quests.filter(q=>!q.completed).length}</span></button></div>
      </aside>
      <section className="center-column">
        <div className="map-frame">
          <div className="map-topline"><span><i className={running(world)?'live-dot':'paused-dot'}/>{running(world)?'小镇实时生活':'时光暂歇'}</span><span><MapPin size={12}/> {regionAt(world.player.x,world.player.y).name} · {daylight(world.clock).phase}</span><div className="view-actions">{immersive&&<><span className="immersive-clock">第 {dayOf(world.clock)} 天 · {timeOf(world.clock)} · {world.weather} · 实际 {(running(world)?world.timing?.actualMultiplier??0:0).toFixed(2)}×</span><button onClick={()=>void run(()=>api('/control',{action:running(world)?'pause':'resume'}))}>{running(world)?<Pause size={14}/>:<Play size={14}/>} {running(world)?'暂停模拟':'继续模拟'}</button></>}<button ref={fullscreenButton} aria-label={immersive?'退出全屏':'全屏观看'} onClick={()=>void toggleFullscreen()}>{immersive?<Minimize2 size={14}/>:<Maximize2 size={14}/>} {immersive?'退出全屏':'全屏观看'}</button></div></div>
          <TownCanvas snapshot={world} selected={selected} onSelect={setSelected} onMove={(x,y)=>{setAutoTalk(null);if(running(world))void command('move',{x,y}).catch(e=>setError(e.message));}} onInteract={interact}/>
          {!running(world)&&<div className="pause-tag"><Pause size={12}/> {world.status==='paused_budget_limit'?'金额池额度不足':'世界已暂停'}<span>记忆与故事仍在这里</span></div>}
          <div className="map-bottomline"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> 移动 <span className="key-gap"/><kbd>E</kbd> 交谈</span><span>也可以点击道路，让脚步慢下来。</span><button aria-label="保存当前小镇" onClick={()=>void run(async()=>{await api('/saves',{label:`春日 ${dayOf(world.clock)} · ${timeOf(world.clock)}`});setError('小镇和记忆已保存。');})}><Save size={15}/></button></div>
          {conversation&&<section className="dialogue-box" aria-label="对话框"><header><span><MessageCircle size={16}/> 与{world.actors.find(a=>conversation.participants.includes(a.id))?.name}交谈</span><button className="icon-button" aria-label="结束对话" onClick={()=>void run(()=>command('end'))}><X size={17}/></button></header><div className="chat-messages">{conversation.messages.length===0&&<p className="empty-chat">你走到对方面前。说声你好，让故事从这里开始。</p>}{conversation.messages.map(m=><div className={`chat-line ${m.speaker==='player'?'you':''}`} key={m.id}><b>{m.speaker==='player'?'你':world.actors.find(a=>a.id===m.speaker)?.name}</b><p>{m.text}</p><small>{m.source}</small></div>)}{conversation.pending&&<p className="thinking-message">对方正在想一想 <span>· · ·</span></p>}<div ref={chatBottom}/></div><form onSubmit={send}><label className="sr-only" htmlFor="dialogue-input">对话内容</label><input id="dialogue-input" placeholder={running(world)?'有什么想对 TA 说的？':'模拟已暂停，输入可保留'} maxLength={1000} value={text} onChange={e=>setText(e.target.value)} autoComplete="off" onKeyDown={e=>{if(e.nativeEvent.isComposing&&e.key==='Enter')e.preventDefault();}}/><button aria-label="发送消息" disabled={!running(world)||!text.trim()||sending||conversation.pending}><Send size={17}/></button></form></section>}
        </div>
        <section className="outdoor-summary" aria-label="玩家户外状态"><div className="outdoor-status-icon"><Compass size={22}/></div><div className="outdoor-status-copy"><strong>{outdoorTask?`${outdoorTask.phase==='travel'?'前往':'正在'}${location(outdoorTask.place).name} · ${outdoorActivities[outdoorTask.kind].name}`:'今天，想去哪里？'}</strong><span>{outdoorTask?outdoorTask.phase==='travel'?'沿途欣赏风景，到达后自动开始':`还需 ${Math.max(0,Math.ceil(outdoorTask.endsAt!-world.clock))} 游戏分钟`:(world.player.outdoor.lastResult?.text??'海岸、湖畔、山地与林间，都有新的生活。')}</span>{outdoorTask?.phase==='active'&&<div className="outdoor-progress"><i style={{width:`${outdoorProgress}%`}}/></div>}</div><span className="player-energy"><BatteryMedium size={15}/>{Math.round(world.player.energy)}</span>{outdoorTask?<button className="outline" disabled={!running(world)} onClick={()=>void run(()=>command('cancel-outdoor'))}>结束活动</button>:<button className="primary" onClick={()=>setModal('outdoors')}>出门探索<ArrowRight size={14}/></button>}</section>
        <section className="timeline"><header><div><Activity size={16}/><h2>小镇此刻</h2><span>生活从细节里发生</span></div><select aria-label="事件类型" value={eventFilter} onChange={e=>setEventFilter(e.target.value)}><option value="all">全部动态</option><option value="social">人物互动</option><option value="outdoor">户外活动</option><option value="weather">天气变化</option><option value="family">婚姻与孩子</option><option value="justice">冲突与司法</option></select></header><div className="timeline-content">{recent.map(e=><div className="event-row" key={e.id}><time>{timeOf(e.at)}</time><span className={`event-dot ${e.kind}`}/><p>{e.text}</p>{e.mode==='offline_compressed'&&<small>离线</small>}</div>)}{!recent.length&&<p className="empty-state">世界很安静。让时间开始流动吧。</p>}</div></section>
      </section>
      <aside className="inspector">
        <div className="inspector-top"><span className="section-label">{observer?'人物观察':'居民档案'}</span>{observer&&<span className="private-label"><Eye size={11}/> 管理员视角</span>}</div>
        <div className="profile-hero"><Avatar actor={actor} large/><div><h1>{actor.name}</h1><p>{actor.role} <span>·</span> {location(actor.home).name}</p><div className="personality">{actor.life.status==='dead'?'已故 · 档案保留':actor.life.custody?'服刑中':actor.life.stage==='child'?'幼年 · 被照护':tags[actor.id]??'新邻居 · 独立的故事'}</div></div></div>
        <div className="tabs" role="tablist" aria-label="人物资料"><button role="tab" aria-selected={tab==='profile'} className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>此刻</button><button role="tab" aria-selected={tab==='memory'} className={tab==='memory'?'active':''} onClick={()=>setTab('memory')}>记忆</button><button role="tab" aria-selected={tab==='relations'} className={tab==='relations'?'active':''} onClick={()=>setTab('relations')}>关系</button>{observer&&<button role="tab" aria-selected={tab==='secret'} className={tab==='secret'?'active':''} onClick={()=>setTab('secret')}>秘密</button>}</div>
        <div className="inspector-content" role="tabpanel">
          {tab==='profile'&&<><div className="activity-card"><span><span className="status-dot"/> 正在发生</span><strong>{actor.activity}</strong><small>{actor.busy?'决策请求进行中':'按照自己的节奏生活'}</small></div><div className="life-summary"><span>{actor.life.spouse?`配偶：${world.actors.find(a=>a.id===actor.life.spouse)?.name}`:actor.life.stage==='child'?'在家人照护下成长':'尚未结婚'}</span><span>{actor.life.children.length} 位孩子{actor.life.custody?` · 第 ${dayOf(actor.life.custody.releaseAt)} 天刑满`:actor.life.status==='dead'?` · 第 ${dayOf(actor.life.diedAt!)} 天离世`:''}</span></div><div className="vitals"><div><span>心情</span><strong>{actor.mood}</strong></div><div><span>精力</span><strong>{Math.round(actor.energy)}<small>/100</small></strong></div></div><div className="energy-track"><i style={{width:`${actor.energy}%`}}/></div>{privateActor?<><div className="detail-section"><h3><Leaf size={14}/> 心里的方向</h3><p>{privateActor.goal}</p></div><div className="detail-section"><h3><Clock3 size={14}/> 接下来的打算</h3><p>{privateActor.plan}</p></div><DecisionCard decision={decision}/>{world.actionTraces?.find(t=>t.actorId===actor.id)&&<p className="trace-short">最新行动追踪：{({requesting:'模型请求中',deferred:'暂停暂存',applied:'已交给游戏执行',overridden:'规则替换后执行',rejected:'执行被拒绝',failed:'请求失败',interrupted:'中断待核对'})[world.actionTraces.find(t=>t.actorId===actor.id)!.status]}</p>}<button className="outline lab-open" onClick={()=>setModal('lab')}><Activity size={15}/> Jev 决策实验室</button></>:<div className="private-empty"><Shield size={20}/><p>你知道 TA 正在做什么，<br/>但还不知道 TA 心里在想什么。</p><small>通过交谈，一点点了解彼此。</small></div>}</>}
          {tab==='memory'&&(privateActor?<><div className="section-heading"><h3>记忆手札</h3><button onClick={()=>void openDocs()}><FileText size={13}/> 编辑文档</button></div><p className="muted small">只属于{actor.name}的经历与理解</p>{[...privateActor.memories].reverse().slice(0,30).map(m=><article className="memory-entry" key={m.id}><span>第 {m.day} 天 · {timeOf(m.minute)}{m.important&&<i>长期</i>}</span><p>{m.text}</p><small>{m.kind==='belief'?'个人认知 / 转述':m.kind==='reflection'?'日终反思':m.kind==='editor'?'管理员设定':'亲身经历'}</small></article>)}</>:<div className="private-empty"><BookOpen/><p>这是 TA 的私人手札。</p><small>游玩模式不会读取村民的私有记忆。</small></div>)}
          {tab==='relations'&&(privateActor?<><h3 className="relationship-title">人与人之间，总有些不同</h3>{Object.entries(privateActor.relations).sort((a,b)=>b[1].affection-a[1].affection).map(([id,r])=><div className="relation-row" key={id}><div><strong>{id==='player'?'你':world.actors.find(a=>a.id===id)?.name}</strong><span>{privateActor.life.spouse===id?'配偶':privateActor.life.parents.includes(id)?'家长':privateActor.life.children.includes(id)?'孩子':privateActor.partner===id?'恋人':r.resentment>25?'有些芥蒂':r.affection>35?'亲近':r.affection<0?'疏远':'相识'}</span></div><div className="relation-bars"><span><Heart size={11}/> 好感 {Math.round(r.affection)}</span><i><b style={{width:`${Math.max(0,r.affection)}%`}}/></i><span><Shield size={11}/> 信任 {Math.round(r.trust)} · 吸引 {Math.round(r.attraction)}</span></div></div>)}</>:<div className="private-empty"><Heart/><p>关系藏在一次次回应里。</p><small>精确关系数值仅供管理员观察。</small></div>)}
          {tab==='secret'&&privateActor&&<><div className="secret-warning"><LockKeyhole size={15}/><span>只有管理员与本人能看到核心秘密。</span></div><div className="secret-core"><span>内心深处</span><p>{privateActor.secret.core}</p></div><h3 className="section-label">谁听过哪些片段</h3>{Object.keys(privateActor.secret.disclosed).length?Object.entries(privateActor.secret.disclosed).map(([id,fragments])=><div className="knowledge-card" key={id}><b>{id==='player'?'你':world.actors.find(a=>a.id===id)?.name}</b>{fragments.map(i=><p key={i}>L{i+1} · {privateActor.secret.fragments[i]}</p>)}</div>):<p className="empty-secret">还没有向任何人吐露。<br/>信任需要真实的经历来积累。</p>}<button className="outline full" onClick={()=>void openDocs()}><FileText size={14}/> 编辑私有设定</button></>}
        </div>
        <div className="inspector-actions"><button className="outline full inspector-story-button" onClick={()=>setModal('story')}><BookOpen size={15}/> 人物故事 <Sparkles size={13}/></button><button className="primary full" disabled={actor.life.status==='dead'||!!actor.life.custody} onClick={()=>void talk()}><MessageCircle size={16}/>{autoTalk===actor.id?'正在走近…':distance(world.player,actor)>4?'走近，聊一聊':'和 TA 聊一聊'}<ArrowRight size={15}/></button><div><button className="outline" onClick={()=>setModal('inventory')}><Heart size={14}/> 送份礼物</button><button className="outline" onClick={()=>void run(()=>command('invite',{target:actor.id}))}><Sun size={14}/> 邀约</button></div></div>
      </aside>
    </main>
    <footer className="statusbar"><span><Leaf size={12}/> 一个有记忆的小镇，一场持续生长的生活。</span><button onClick={()=>setModal('settings')}><Zap size={12}/><span className="budget-status">{budgetProviders.map(provider=><span key={provider}>{provider} {money(world.usage.pools[provider].spentCny)} / {money(world.usage.pools[provider].limitCny)}</span>)}</span></button><span>{`${world.actors.filter(a=>a.busy).length} 位居民正在思考`}</span></footer>
    {error&&<div className="toast" role="status"><span>{error}</span><button onClick={()=>setError('')} aria-label="关闭提示"><X size={15}/></button></div>}
    {world.status==='paused_budget_limit'&&<div className="budget-alert" role="alert"><Pause size={15}/><span>模型金额池额度不足，世界停在了这一刻。</span><button onClick={()=>setModal('settings')}>调整上限</button></div>}
    {modal==='story'&&<Modal title={`${actor.name}的人物故事`} close={()=>setModal(null)} wide><ActorStory key={`${world.id}:${actor.id}:${observer}`} actorId={actor.id} view={observer?'observer':'player'}/></Modal>}
    {modal==='lab'&&observer&&<Modal title="Jev 决策实验室" close={()=>setModal(null)} wide><DecisionLab world={world} selected={selected}/></Modal>}
    {modal==='society'&&<Modal title="溪谷生活簿 · 家庭与司法" close={()=>setModal(null)} wide><div className="society-stats"><div><strong>{world.actors.filter(a=>a.life.status==='alive').length}</strong><span>在世居民</span></div><div><strong>{world.actors.filter(a=>a.life.spouse&&a.life.status==='alive'&&a.id<a.life.spouse).length}</strong><span>婚姻家庭</span></div><div><strong>{world.actors.filter(a=>a.life.custody).length}</strong><span>正在服刑</span></div></div><p className="hint">婚姻需要双方独立同意。婚后每日最多一次 20% 育儿机会，双方同意后等待 2 天；每位家长最多 2 个孩子，全镇上限 48 人。这是加速的家庭模拟。</p><h3>家庭与新生命</h3><div className="family-grid">{world.actors.filter(a=>a.life.spouse&&a.id<a.life.spouse).map(a=><div className="family-card" key={a.id}><Heart size={17}/><b>{a.name} × {world.actors.find(p=>p.id===a.life.spouse)?.name}</b><small>第 {dayOf(a.life.marriedAt!)} 天结婚 · {a.life.status==='dead'||world.actors.find(p=>p.id===a.life.spouse)?.life.status==='dead'?'家庭纪念档案':'共同生活'}</small><p>{a.life.children.length?a.life.children.map(id=>world.actors.find(p=>p.id===id)?.name).join('、'):'尚无孩子'}</p></div>)}</div>{!world.actors.some(a=>a.life.spouse)&&<p className="muted">有些居民已经交往，是否结婚由他们自己决定。</p>}{world.society.births.map(b=><p className="family-pending" key={b.id}>{b.parents.map(id=>world.actors.find(a=>a.id===id)?.name).join(' 与 ')} · 预计第 {dayOf(b.dueAt)} 天 {timeOf(b.dueAt)} 迎接孩子</p>)}<h3>司法所案件</h3><p className="hint">高怨恨与激烈性格可能触发致命冲突，也可以调解或离开。现场记录与独立证词／物证交叉核实后才判刑；服刑 5 个游戏日。画面不表现血腥。</p>{world.society.cases.map(c=><div className="case-card" key={c.id}><div><Shield size={16}/><b>{world.actors.find(a=>a.id===c.victim)?.name}遇害案</b><span>{({investigating:'调查中',unresolved:'证据不足 · 继续调查',sentenced:'已判刑',released:'已刑满'})[c.status]}</span></div><p>第 {dayOf(c.at)} 天 {timeOf(c.at)} 立案{c.releaseAt?` · 第 ${dayOf(c.releaseAt)} 天刑满`:''}</p></div>)}{!world.society.cases.length&&<p className="muted">目前没有案件。高冲突设定也不保证一定发生凶案。</p>}<p className="hint">监内作息：夜间休息、早晚用餐、白天院内放风阅读。孩子由家长或学堂照护；已故居民不再行动，保留记忆档案。</p><div className="button-row"><button className="outline" onClick={()=>void run(()=>command('move',{target:'prison'}))}><MapPin size={14}/> 前往司法所</button><span className="runtime-pill">{world.runtime?.simulation==='worker'?'模拟 Worker 已连接 · 渲染独立运行':'本地模拟'}</span></div></Modal>}
    {modal==='outdoors'&&<Modal title="远行与户外生活" close={()=>setModal(null)} wide><OutdoorPanel world={world} start={(kind,place)=>void run(async()=>{setAutoTalk(null);await command('outdoor',{activity:kind,target:place});setModal(null);})}/></Modal>}
    {modal==='settings'&&<Modal title="小镇运行设置" close={()=>setModal(null)}><div className="settings-section"><h3>模拟模式</h3><div className="mode-options"><button className={world.mode==='live'?'chosen':''} onClick={()=>void run(()=>api('/control',{action:'mode',value:'live'}))}><Sparkles size={20}/><b>真实 Agent</b><span>Jev 决策，DeepSeek 规划与表达</span></button><button className={world.mode==='demo'?'chosen':''} onClick={()=>void run(()=>api('/control',{action:'mode',value:'demo'}))}><Leaf size={20}/><b>规则演示</b><span>验证世界与交互，不消耗 token</span></button></div><p className="hint">切换前需暂停并等待在途请求结束。</p><div className="key-status"><span className={world.configured.jev?'ready':''}><i/> Jev {world.configured.jev?'已配置':'未配置'}</span><span className={world.configured.deepseek?'ready':''}><i/> DeepSeek {world.configured.deepseek?'已配置':'未配置'}</span></div></div><BudgetSettings usage={world.usage} onSave={(provider,value)=>api('/control',{action:'limit',provider,value})} onExchange={value=>api('/control',{action:'exchange',value})}/><div className="settings-section"><h3>实时决策</h3>{observer&&<button className="outline" onClick={()=>setModal('lab')}>打开 Jev 决策实验室</button>}<p className="muted">Jev 行动与对白、后台规划分开排队。任一模型任务未完成时，游戏时间、行走与活动同步等待；任务池仍可并发处理。</p><div className="usage-provider"><strong>当前任务</strong><span>行动 {world.performance?.active.action??0} / {world.performance?.limits.action??12} · 对白 {world.performance?.active.dialogue??0} / 3 · 后台 {world.performance?.active.background??0} / {world.performance?.limits.background??4}</span></div><p className="hint">最近行动请求约 {world.performance?.lastFastContextTokens??0} tokens（输入估算，非计费实测）。模型真实响应耗时仍显示在决策卡上。头顶气泡只展示已确认的对白，省略号表示正在生成回应。</p></div><div className="settings-section"><h3>真实用量</h3>{Object.entries(world.usage.byProvider).map(([provider,u])=><div className="usage-provider" key={provider}><strong>{provider}</strong><span>{compact(u.input)} 输入 · {compact(u.output)} 输出</span><small>{u.latency} ms 平均请求耗时</small></div>)}{!world.usage.calls&&<p className="muted">尚未调用模型。首次开始后记录实际数据。</p>}{world.usage.unknown>0&&<p className="warning">{world.usage.unknown} 个请求用量待核对，已保留额度。</p>}</div><div className="settings-section"><h3>文档与存档</h3><div className="button-row"><button className="outline" onClick={()=>void run(async()=>{const r=await api('/documents/reload',{});setError(r.errors.length?r.errors.join('；'):'文档已扫描并载入。');})}><RefreshCw size={14}/> 立即载入文档</button><button className="outline" onClick={()=>void run(async()=>{setSaveList(await api('/saves'));setModal('saves');})}><Save size={14}/> 管理存档</button></div><p className="hint">编辑目录每 30 秒检查，稳定两轮后载入。冲突保留旧版本。</p>{world.documentErrors?.map(e=><p className="warning" key={e}>{e}</p>)}</div></Modal>}
    {modal==='inventory'&&<Modal title="口袋里的小心意" close={()=>setModal(null)}><p className="modal-intro">一束花，一份面包。礼物有分量，真心也是。<br/>当前选中：<b>{actor.name}</b> · 你的金币：{world.player.coins}</p><div className="item-grid">{Object.entries(items).map(([id,item])=><div className="item-card" key={id}><span className="item-pixel" style={{background:item.color}}>{id==='flowers'?'✿':id==='wood'?'▥':id==='book'?'▤':'◆'}</span><b>{item.name}</b><small>拥有 {world.player.inventory[id]??0} 份</small><div><button disabled={!world.player.inventory[id]} onClick={()=>void run(()=>command('gift',{target:actor.id,item:id}))}>赠送</button><button onClick={()=>void run(()=>command('buy',{item:id}))}>买 · {item.price}</button></div></div>)}</div><div className="button-row"><button className="outline" onClick={()=>void run(()=>command('move',{target:'market'}))}><MapPin size={14}/> 去杂货铺</button><button className="outline" onClick={()=>void run(()=>command('work'))}><Leaf size={14}/> 在附近帮工</button></div><p className="hint">赠礼与购买需走近对方或店铺。花圃、河岸、作坊可以帮工。</p></Modal>}
    {modal==='quests'&&<Modal title="溪谷公告板" close={()=>setModal(null)}><p className="modal-intro">有些事，一个人做不完。<br/>让共同的经历，成为共同的记忆。</p>{world.quests.map(q=><div className="quest-card" key={q.id}><span className="quest-icon">{q.id==='bridge'?<Flag size={24}/>:<Flower2 size={24}/>}</span><div><h3>{q.title}{q.completed&&<Check size={15}/>}</h3><p>{q.text}</p><div className="budget-meter"><i style={{width:`${q.progress/q.required*100}%`}}/></div><small>{q.progress} / {q.required} · 完成奖励 {q.reward} 金币</small><div className="button-row"><button className="outline" onClick={()=>void run(()=>command('move',{target:q.id==='bridge'?'bridge':'square'}))}>前往地点</button><button className="primary" disabled={q.completed} onClick={()=>void run(()=>command('contribute',{target:q.id}))}>贡献一份{q.id==='bridge'?'木材':'花束 / 面包'}</button></div></div></div>)}<div className="settings-section"><h3>与你有关的约定</h3>{world.appointments.filter(p=>p.from==='player'||p.to==='player').map(p=><p key={p.id} className="appointment-row">第 {dayOf(p.at)} 天 {timeOf(p.at)} · 河岸散步 <b>{({accepted:'已约好',fulfilled:'已赴约',missed:'错过了',declined:'已婉拒',proposed:'待答复'})[p.status]}</b></p>)}<div className="button-row"><button className="outline" onClick={()=>void run(()=>command('confess',{target:actor.id}))}><Heart size={14}/> 向{actor.name}表达心意</button><button className="outline" onClick={()=>void run(()=>command('apologize',{target:actor.id}))}>真诚道歉</button>{privateActor?.partner==='player'&&<button className="outline" onClick={()=>void run(()=>command('breakup',{target:actor.id}))}>结束恋爱关系</button>}</div></div></Modal>}
    {modal==='docs'&&<Modal title={`${actor.name}的可编辑文档`} close={()=>setModal(null)} wide><p className="modal-intro">保留头部的文档 ID 与版本号。角色只会载入自己的文档，修改不会改写世界事实。</p><div className="doc-tabs">{docs.map((d,i)=><button key={d.id} className={docIndex===i?'active':''} onClick={()=>{setDocIndex(i);setDocText(d.text);}}>{['人设','深层秘密','长期设定','当日记忆'][i]}</button>)}</div><label className="sr-only" htmlFor="document-editor">Markdown 文档</label><textarea id="document-editor" className="document-editor" value={docText} onChange={e=>setDocText(e.target.value)} spellCheck={false}/><p className="hint file-path">{docs[docIndex]?.file}</p>{docs[docIndex]?.error&&<p className="warning">{docs[docIndex].error}</p>}<div className="button-row"><button className="primary" onClick={()=>void run(async()=>{const updated=await api<DocumentView[]>('/documents',{id:docs[docIndex].id,revision:docs[docIndex].revision,text:docText});setDocs(updated);setDocText(updated[docIndex].text);setError('修改已载入，旧决策会重新校验。');})}><Check size={15}/> 保存并载入</button><button className="outline" onClick={()=>void openDocs()}><RefreshCw size={14}/> 重新读取</button></div></Modal>}
    {modal==='saves'&&<Modal title="小镇存档" close={()=>setModal(null)}><button className="primary" onClick={()=>void run(async()=>{await api('/saves',{label:`第${dayOf(world.clock)}天 ${timeOf(world.clock)}`});setSaveList(await api('/saves'));})}><Save size={15}/> 保存这一刻</button>{saveList.map(s=><div className="save-row" key={s.id}><span><b>{s.label}</b><small>{new Date(s.created).toLocaleString()}</small></span><button className="outline" onClick={()=>void run(async()=>{await api(`/saves/${s.id}/restore`,{});setError('已恢复存档，token 消耗保持不变。');setModal(null);})}>恢复</button></div>)}<p className="hint">恢复前请暂停并等待模型请求结束。恢复世界不会撤销已发生的 token 消耗。</p></Modal>}
    {modal==='help'&&<Modal title="在溪谷镇生活" close={()=>setModal(null)}><div className="help-list"><p><b>全屏与天气</b>地图右上角「全屏观看」进入沉浸视野，Esc 或退出按钮返回。昼夜随游戏时间变化；天气每四个游戏小时演变，并影响居民计划、移动、户外体力与活动开放。星光按钮可关闭泛光、景深与雨滴，保留真实天气规则。旋转按钮可改变 Three.js 斜视镜头方向。</p><p><b>大地图</b>点击区域名切换视野，拖动浏览、滚轮缩放；全域地图查看六个地区。跟随玩家按钮将镜头带回你身边。</p><p><b>远行与活动</b>选择海钓、湖钓、慢跑、篮球、登山或打猎，自动走到活动点。钓鱼消耗鱼饵，打猎消耗箭矢，体力不足先休息。</p><p><b>走一走</b>点击道路或使用 WASD / 方向键移动。E 与最近的村民交谈。</p><p><b>认识一个人</b>点击村民查看档案。靠近后聊天、送礼、邀约；对方可以拒绝。</p><p><b>让时间流动</b>速率滑块设置目标倍率；模型请求未完成时，游戏时间、走路与活动一起等待，实际倍率显示近 5 秒的测量值。暂停会停止世界、村民行动和新模型请求。在途请求继续结算。关闭后端后游戏时间停止，下次启动从保存的进度继续，不补算停机时间。</p><p><b>观察故事背后</b>观察者模式能查看私有记忆、秘密、关系与 Jev 概率；游玩模式隐藏这些信息。</p><p><b>从一件小事开始</b>在花圃、河岸或作坊帮工，用真实物品为集市和旧桥出力。</p><p><b>模型分工</b>Jev 做类型化决定，DeepSeek 提供宏观规划与文字表达；规则演示不调用模型。</p></div></Modal>}
  </div>;
}
function locationProtocol(){return window.location.protocol==='https:'?'wss:':'ws:';}
function DecisionCard({decision}:{decision?:Snapshot['decisions'] extends (infer T)[]|undefined?T:never}){
  if(!decision)return <div className="decision-card waiting"><div><Sparkles size={14}/><b>Jev 的下一步</b></div><p>时间开始后，这里会出现真实的选择、概率与依据。</p></div>;
  return <div className="decision-card"><div><Sparkles size={14}/><b>{decision.source.includes('规则')?'规则演示记录':'最近一次决策'}</b><small>单次响应 {decision.latency} ms</small></div><p>{decision.action}</p>{Object.entries(decision.choices).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([key,p])=><div className="probability" key={key}><span>{key}</span><i><b style={{width:`${p*100}%`}}/></i><small>{Math.round(p*100)}%</small></div>)}{decision.confidence!==null&&<footer>置信度 {Math.round(decision.confidence*100)}% <span>·</span> {compact(decision.input+decision.output)} token</footer>}{decision.error&&<p className="warning">{decision.error}</p>}</div>;
}
